### ISSUE TITLE
Tweakers Scorecards not readable

### ISSUE THREAD

**Issue by HiddevH** [ArnoutPullen/MaterialDarkModeExtension#1]
Hey,

The Tweakers score cards (and pricewatch) window within reviews are not properly readable.
Could you adjust this a bit?

Cheers for the great work really like the extension otherwise :-)

![image](https://user-images.githubusercontent.com/19668789/48827135-97925280-ed6c-11e8-86dc-9d28ee982553.png)

**Comment by ArnoutPullen** [comment]
Hello HiddevH,

Thanks for your feedback!
I just released a new version with this fixed.
In about one hour it wil be visible public.
